### ISSUE TITLE
cant changes messages.yml

### ISSUE THREAD

**Issue by MartinPej** [ShayPunter/QuickSell#2]
## Description (Required)
Changing the messages config, saving and then reloading doesn't change anything, I then get that error message. When I restart the server the config goes back to its default setting.

## Steps to reproduce the Issue (Required)
change the messages config and reload the plugin.

## Expected behavior (Required)
a changed config file

## Server Log / Error Report
[00:45:56 WARN]: java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Method.invoke(Object, Object[])" because "me.mrCookieSlime.QuickSell.utils.StringUtils.getName" is null
[00:45:56 WARN]:        at quicksell.v2.3.2.jar//me.mrCookieSlime.QuickSell.utils.StringUtils.formatItemName(StringUtils.java:32)
[00:45:56 WARN]:        at quicksell.v2.3.2.jar//me.mrCookieSlime.QuickSell.PriceInfo.<init>(PriceInfo.java:49)
[00:45:56 WARN]:        at quicksell.v2.3.2.jar//me.mrCookieSlime.QuickSell.Shop.<init>(Shop.java:37)
[00:45:56 WARN]:        at quicksell.v2.3.2.jar//me.mrCookieSlime.QuickSell.QuickSell.reload(QuickSell.java:188)
[00:45:56 WARN]:        at quicksell.v2.3.2.jar//me.mrCookieSlime.QuickSell.commands.QuickSellCommand.onReload(QuickSellCommand.java:35)
[00:45:56 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[00:45:56 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[00:45:56 WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[00:45:56 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[00:45:56 WARN]:        at quicksell.v2.3.2.jar//me.mrCookieSlime.QuickSell.acf.RegisteredCommand.invoke(RegisteredCommand.java:152)
[00:45:56 WARN]:        at quicksell.v2.3.2.jar//me.mrCookieSlime.QuickSell.acf.BaseCommand.executeCommand(BaseCommand.java:577)
[00:45:56 WARN]:        at quicksell.v2.3.2.jar//me.mrCookieSlime.QuickSell.acf.BaseCommand.execute(BaseCommand.java:513)
[00:45:56 WARN]:        at quicksell.v2.3.2.jar//me.mrCookieSlime.QuickSell.acf.RootCommand.execute(RootCommand.java:99)
[00:45:56 WARN]:        at quicksell.v2.3.2.jar//me.mrCookieSlime.QuickSell.acf.BukkitRootCommand.execute(BukkitRootCommand.java:81)
[00:45:56 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[00:45:56 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:911)
[00:45:56 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64)
[00:45:56 WARN]:        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264)
[00:45:56 WARN]:        at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:305)
[00:45:56 WARN]:        at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:289)
[00:45:56 WARN]:        at net.minecraft.server.network.PlayerConnection.b(PlayerConnection.java:2295)
[00:45:56 WARN]:        at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$20(PlayerConnection.java:2249)
[00:45:56 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
[00:45:56 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[00:45:56 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[00:45:56 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[00:45:56 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[00:45:56 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1360)
[00:45:56 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185)
[00:45:56 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[00:45:56 WARN]:        at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1337)
[00:45:56 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1330)
[00:45:56 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[00:45:56 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1308)
[00:45:56 WARN]:        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1196)
[00:45:56 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
[00:45:56 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[00:45:56 WARN]: java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Method.invoke(Object, Object[])" because "me.mrCookieSlime.QuickSell.utils.StringUtils.getName" is null
[00:45:56 WARN]:        at quicksell.v2.3.2.jar//me.mrCookieSlime.QuickSell.utils.StringUtils.formatItemName(StringUtils.java:32)
[00:45:56 WARN]:        at quicksell.v2.3.2.jar//me.mrCookieSlime.QuickSell.PriceInfo.<init>(PriceInfo.java:49)
[00:45:56 WARN]:        at quicksell.v2.3.2.jar//me.mrCookieSlime.QuickSell.Shop.<init>(Shop.java:37)
[00:45:56 WARN]:        at quicksell.v2.3.2.jar//me.mrCookieSlime.QuickSell.QuickSell.reload(QuickSell.java:188)
[00:45:56 WARN]:        at quicksell.v2.3.2.jar//me.mrCookieSlime.QuickSell.commands.QuickSellCommand.onReload(QuickSellCommand.java:35)
[00:45:56 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[00:45:56 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[00:45:56 WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[00:45:56 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[00:45:56 WARN]:        at quicksell.v2.3.2.jar//me.mrCookieSlime.QuickSell.acf.RegisteredCommand.invoke(RegisteredCommand.java:152)
[00:45:56 WARN]:        at quicksell.v2.3.2.jar//me.mrCookieSlime.QuickSell.acf.BaseCommand.executeCommand(BaseCommand.java:577)
[00:45:56 WARN]:        at quicksell.v2.3.2.jar//me.mrCookieSlime.QuickSell.acf.BaseCommand.execute(BaseCommand.java:513)
[00:45:56 WARN]:        at quicksell.v2.3.2.jar//me.mrCookieSlime.QuickSell.acf.RootCommand.execute(RootCommand.java:99)
[00:45:56 WARN]:        at quicksell.v2.3.2.jar//me.mrCookieSlime.QuickSell.acf.BukkitRootCommand.execute(BukkitRootCommand.java:81)
[00:45:56 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[00:45:56 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:911)
[00:45:56 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64)
[00:45:56 WARN]:        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264)
[00:45:56 WARN]:        at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:305)
[00:45:56 WARN]:        at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:289)
[00:45:56 WARN]:        at net.minecraft.server.network.PlayerConnection.b(PlayerConnection.java:2295)
[00:45:56 WARN]:        at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$20(PlayerConnection.java:2249)
[00:45:56 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
[00:45:56 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[00:45:56 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[00:45:56 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[00:45:56 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[00:45:56 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1360)
[00:45:56 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185)
[00:45:56 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[00:45:56 WARN]:        at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1337)
[00:45:56 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1330)
[00:45:56 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[00:45:56 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1308)
[00:45:56 WARN]:        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1196)
[00:45:56 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
[00:45:56 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

## Environment (Required)

 - Minecraft Version: Paper 1.19.2
 - QuickSell Version: 2.3.2

**Comment by MartinPej** [comment]
By the looks of this server startup error it seems you might just need to add some things for the 1.19 versions.


[01:17:38 WARN]: java.lang.ClassNotFoundException: net.minecraft.server.v1_19_R1.EntityPlayer
[01:17:38 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151)
[01:17:38 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
[01:17:38 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[01:17:38 WARN]:        at java.base/java.lang.Class.forName0(Native Method)
[01:17:38 WARN]:        at java.base/java.lang.Class.forName(Class.java:375)
[01:17:38 WARN]:        at quicksell.v2.3.2.jar//me.mrCookieSlime.QuickSell.utils.reflection.ReflectionUtils.getClass(ReflectionUtils.java:236)
[01:17:38 WARN]:        at quicksell.v2.3.2.jar//me.mrCookieSlime.QuickSell.utils.reflection.ReflectionUtils.<clinit>(ReflectionUtils.java:38)
[01:17:38 WARN]:        at quicksell.v2.3.2.jar//me.mrCookieSlime.QuickSell.utils.StringUtils.<clinit>(StringUtils.java:14)
[01:17:38 WARN]:        at quicksell.v2.3.2.jar//me.mrCookieSlime.QuickSell.PriceInfo.<init>(PriceInfo.java:49)
[01:17:38 WARN]:        at quicksell.v2.3.2.jar//me.mrCookieSlime.QuickSell.Shop.<init>(Shop.java:37)
[01:17:38 WARN]:        at quicksell.v2.3.2.jar//me.mrCookieSlime.QuickSell.QuickSell.reload(QuickSell.java:188)
[01:17:38 WARN]:        at quicksell.v2.3.2.jar//me.mrCookieSlime.QuickSell.QuickSell.onEnable(QuickSell.java:101)
[01:17:38 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[01:17:38 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[01:17:38 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542)
[01:17:38 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:565)
[01:17:38 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:479)
[01:17:38 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636)
[01:17:38 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:422)
[01:17:38 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:306)
[01:17:38 WARN]:        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1125)
[01:17:38 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
[01:17:38 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[01:17:38 WARN]: java.lang.ClassNotFoundException: net.minecraft.server.v1_19_R1.ItemStack
[01:17:38 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151)
[01:17:38 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
[01:17:38 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[01:17:38 WARN]:        at java.base/java.lang.Class.forName0(Native Method)
[01:17:38 WARN]:        at java.base/java.lang.Class.forName(Class.java:375)
[01:17:38 WARN]:        at quicksell.v2.3.2.jar//me.mrCookieSlime.QuickSell.utils.reflection.ReflectionUtils.getClass(ReflectionUtils.java:236)
[01:17:38 WARN]:        at quicksell.v2.3.2.jar//me.mrCookieSlime.QuickSell.utils.StringUtils.<clinit>(StringUtils.java:15)
[01:17:38 WARN]:        at quicksell.v2.3.2.jar//me.mrCookieSlime.QuickSell.PriceInfo.<init>(PriceInfo.java:49)
[01:17:38 WARN]:        at quicksell.v2.3.2.jar//me.mrCookieSlime.QuickSell.Shop.<init>(Shop.java:37)
[01:17:38 WARN]:        at quicksell.v2.3.2.jar//me.mrCookieSlime.QuickSell.QuickSell.reload(QuickSell.java:188)
[01:17:38 WARN]:        at quicksell.v2.3.2.jar//me.mrCookieSlime.QuickSell.QuickSell.onEnable(QuickSell.java:101)
[01:17:38 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[01:17:38 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[01:17:38 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542)
[01:17:38 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:565)
[01:17:38 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:479)
[01:17:38 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636)
[01:17:38 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:422)
[01:17:38 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:306)
[01:17:38 WARN]:        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1125)
[01:17:38 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
[01:17:38 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[01:17:38 WARN]: java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Method.invoke(Object, Object[])" because "me.mrCookieSlime.QuickSell.utils.StringUtils.getName" is null
[01:17:38 WARN]:        at quicksell.v2.3.2.jar//me.mrCookieSlime.QuickSell.utils.StringUtils.formatItemName(StringUtils.java:32)
[01:17:38 WARN]:        at quicksell.v2.3.2.jar//me.mrCookieSlime.QuickSell.PriceInfo.<init>(PriceInfo.java:49)
[01:17:38 WARN]:        at quicksell.v2.3.2.jar//me.mrCookieSlime.QuickSell.Shop.<init>(Shop.java:37)
[01:17:38 WARN]:        at quicksell.v2.3.2.jar//me.mrCookieSlime.QuickSell.QuickSell.reload(QuickSell.java:188)
[01:17:38 WARN]:        at quicksell.v2.3.2.jar//me.mrCookieSlime.QuickSell.QuickSell.onEnable(QuickSell.java:101)
[01:17:38 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[01:17:38 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[01:17:38 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542)
[01:17:38 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:565)
[01:17:38 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:479)
[01:17:38 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636)
[01:17:38 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:422)
[01:17:38 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:306)
[01:17:38 WARN]:        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1125)
[01:17:38 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
[01:17:38 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[01:17:38 WARN]: java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Method.invoke(Object, Object[])" because "me.mrCookieSlime.QuickSell.utils.StringUtils.getName" is null
[01:17:38 WARN]:        at quicksell.v2.3.2.jar//me.mrCookieSlime.QuickSell.utils.StringUtils.formatItemName(StringUtils.java:32)
[01:17:38 WARN]:        at quicksell.v2.3.2.jar//me.mrCookieSlime.QuickSell.PriceInfo.<init>(PriceInfo.java:49)
[01:17:38 WARN]:        at quicksell.v2.3.2.jar//me.mrCookieSlime.QuickSell.Shop.<init>(Shop.java:37)
[01:17:38 WARN]:        at quicksell.v2.3.2.jar//me.mrCookieSlime.QuickSell.QuickSell.reload(QuickSell.java:188)
[01:17:38 WARN]:        at quicksell.v2.3.2.jar//me.mrCookieSlime.QuickSell.QuickSell.onEnable(QuickSell.java:101)
[01:17:38 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[01:17:38 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[01:17:38 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542)
[01:17:38 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:565)
[01:17:38 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:479)
[01:17:38 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636)
[01:17:38 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:422)
[01:17:38 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:306)
[01:17:38 WARN]:        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1125)
[01:17:38 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
[01:17:38 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by MartinPej** [comment]
Tried on 1.16.5, still getting the same issue but no error codes are shown

**Comment by ShayPunter** [comment]
Hi @Njordyr could you post your messages.yml file here?

**Comment by MartinPej** [comment]
messages:
  sell: '&a&l+ ${MONEY} &7[ &eSold &o{ITEMS} &eItems&7 ]'
  no-access: '&4You do not have access to this Shop'
  total: '&2TOTAL: &6+ ${MONEY}'
  get-nothing: '&4Sorry, but you will get nothing for these Items :('
  dropped: '&cYou have been given back some of your Items because you could not sell
    them...'
  no-permission: '&cYou do not have the required Permission to do this!'
  unknown-shop: '&cUnknown Shop!'
  no-items: '&cSorry, but you have no Items that can be sold!'
  estimate: '&eYou will get &6${MONEY} &efor these Items'
  booster-use:
    MONETARY: '&a&l+ ${MONEY} &7(&e%multiplier%x Booster &7&oHover for more Info &7)'
    PRISONGEMS: '&7+ &a{GEMS} &7(&e%multiplier%x Booster &7&oHover for more Info &7)'
  pbooster-use:
    MONETARY: '&a&l+ ${MONEY} &7(&e%multiplier%x Booster &7&oHover for more Info &7)'
    PRISONGEMS: '&7+ &a{GEMS} &7(&e%multiplier%x Booster &7&oHover for more Info &7)'
commands:
  booster:
    permission: '&cYou do not have permission to activate a Booster!'
  permission: '&cYou do not have permission for this!'
  usage: '&4Usage: &c%usage%'
  reload:
    done: '&7All Shops have been reloaded!'
  price-set: '&7%item% is now worth &a$%price% &7in the Shop %shop%'
  shop-created: '&7You successfully created a new Shop called &b%shop%'
  shop-deleted: '&cYou successfully deleted the Shop called &4%shop%'
  sellall:
    usage: '&4Usage: &c/sellall <Shop>'
  disabled: '&cThis command has been disabled'
  prices:
    usage: '&4Usage: &c/prices <Shop>'
    permission: '&cYou do not have permission for this!'
menu:
  accept: '&a> Click to sell'
  estimate: '&e> Click to estimate'
  cancel: '&c> Click to cancel'
  title: '&6&l$ Sell your Items $'
booster:
  reset: '&cReset %player%''s multiplier to 1.0x'
  extended:
    MONETARY: '&6%player% &ehas extended the %multiplier%x Booster (Money) for %time%
      more Minute/s'
    EXP: '&6%player% &ehas extended the %multiplier%x Booster (Experience) for %time%
      more Minute/s'
    MCMMO: '&6%player% &ehas extended the %multiplier%x Booster (mcMMO) for %time%
      more Minute/s'
    PRISONGEMS: '&6%player% &ehas extended the %multiplier%x Booster (Gems) for %time%
      more Minute/s'
  activate:
    MONETARY: '&6&l%player% &ehas activated a %multiplier%x Booster (Money) for %time%
      Minute/s'
    EXP: '&6&l%player% &ehas activated a %multiplier%x Booster (Experience) for %time%
      Minute/s'
    MCMMO: '&6&l%player% &ehas activated a %multiplier%x Booster (mcMMO) for %time%
      Minute/s'
    PRISONGEMS: '&6&l%player% &ehas activated a %multiplier%x Booster (Gems) for %time%
      Minute/s'
  deactivate:
    MONETARY: '&4%player%''s &c%multiplier%x Booster (Money) wore off!'
    EXP: '&4%player%''s &c%multiplier%x Booster (Experience) wore off!'
    MCMMO: '&4%player%''s &c%multiplier%x Booster (mcMMO) wore off!'
    PRISONGEMS: '&4%player%''s &c%multiplier%x Booster (Gems) wore off!'
boosters:
  reset: '&cReset all Boosters to 1.0x'
editor:
  create-shop:
  - '&a&l! &7Please type in a Name for your Shop in Chat!'
  - '&7&oColor Codes are supported!'
  rename-shop:
  - '&a&l! &7Please type in a Name for your Shop in Chat!'
  - '&7&oColor Codes are supported!'
  renamed-shop:
  - '&a&l! &7Successfully renamed Shop!'
  no-inheritance: '&a&l! &cThis shop has no inheritance'
  set-permission-shop:
  - '&a&l! &7Please type in a Permission for your Shop!'
  - '&7&oType "none" to specify no Permission'
  permission-set-shop: '&a&l! &7Successfully specified a Permission for your Shop!'
pbooster:
  extended:
    MONETARY: '&eYour %multiplier%x Booster (Money) has been extended for %time% more
      Minute/s'
    EXP: '&eYour %multiplier%x Booster (Experience) has been extended for %time% more
      Minute/s'
    MCMMO: '&eYour %multiplier%x Booster (mcMMO) has been extended for %time% more
      Minute/s'
    PRISONGEMS: '&eYour %multiplier%x Booster (Gems) has been extended for %time%
      more Minute/s'
  activate:
    MONETARY: '&eYou have been given a %multiplier%x Booster (Money) for %time% Minute/s'
    EXP: '&eYou have been given a %multiplier%x Booster (Experience) for %time% Minute/s'
    MCMMO: '&eYou have been given a %multiplier%x Booster (mcMMO) for %time% Minute/s'
    PRISONGEMS: '&eYou have been given a %multiplier%x Booster (Gems) for %time% Minute/s'
  deactivate:
    MONETARY: '&4Your &c%multiplier%x Booster (Money) wore off!'
    EXP: '&4Your &c%multiplier%x Booster (Experience) wore off!'
    MCMMO: '&4Your &c%multiplier%x Booster (mcMMO) wore off!'
    PRISONGEMS: '&4Your &c%multiplier%x Booster (Gems) wore off!'

**Comment by ShayPunter** [comment]
Hi @Njordyr,

Appears like the issue might not be residing with the messages file but instead your shop config having an invalid material, can you please post a formatted .yml file of your config?

You can use the code (ctrl + e) to paste formatted yml files

**Comment by MartinPej** [comment]
`options:
  sell-gui-rows: 4
  locked-item: BARRIER
  sign-prefix: '&a[Sell]'
  sellall-sign-prefix: '&a&oSell All'
  pregenerate-all-item-prices: false
  enable-menu-line: false
  enable-commands: true
shop:
  enable-hierarchy: false
  enable-logging: true
boosters:
  extension-mode: false
  refresh-every: 10
commands-on-sell: []
sound:
  enabled: true
  sound: ENTITY_EXPERIENCE_ORB_PICKUP
shops:
  A:
    name: A
    permission: QuickSell.shop.A
    itemtype: CHEST
    lore: []
    amount: 1
    inheritance: []
    price:
      COBBLESTONE: 10.0
      COAL: 80.0
      IRON_INGOT: 100.0
      IRON_BLOCK: 900.0
  B:
    name: B
    amount: 1
    itemtype: CHEST
    lore: []
    permission: QuickSell.shop.B
    inheritance: []
    price:
      COBBLESTONE: 10.0
      COAL: 80.0
      IRON_INGOT: 100.0
      IRON_BLOCK: 900.0
  C:
    name: C
    amount: 1
    itemtype: CHEST
    lore: []
    permission: QuickSell.shop.C
    inheritance: []
    price:
      SANDSTONE: 10.0
      COAL: 80.0
      IRON_INGOT: 100.0
      IRON_BLOCK: 900.0
      GOLD_INGOT: 150.0
      COBBLESTONE: 0.0
list:
- A
- B
- C
`
