### ISSUE TITLE
nothing works java 18 1.19.3

### ISSUE THREAD

**Issue by PREMADESETUPS** [ShayPunter/QuickSell#4]
## Description (Required)

i cant do anything with the plugin
cant add shops
cant reload
it works but i get a massive error pls fix
## Steps to reproduce the Issue (Required)

/quicksell edit A coal_ore 2

## Expected behavior (Required)

not to throw the error maybe?

## Server Log / Error Report

[13:44:38 INFO]: Stoiky issued server command: /quicksell edit A coal_ore 2
[13:44:38 WARN]: java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Method.invoke(Object, Object[])" because "me.mrCookieSlime.QuickSell.utils.StringUtils.getName" is null
[13:44:38 WARN]:        at quicksell v2.3.4.jar//me.mrCookieSlime.QuickSell.utils.StringUtils.formatItemName(StringUtils.java:32)
[13:44:38 WARN]:        at quicksell v2.3.4.jar//me.mrCookieSlime.QuickSell.PriceInfo.<init>(PriceInfo.java:49)
[13:44:38 WARN]:        at quicksell v2.3.4.jar//me.mrCookieSlime.QuickSell.Shop.<init>(Shop.java:37)
[13:44:38 WARN]:        at quicksell v2.3.4.jar//me.mrCookieSlime.QuickSell.QuickSell.reload(QuickSell.java:189)
[13:44:38 WARN]:        at quicksell v2.3.4.jar//me.mrCookieSlime.QuickSell.commands.QuickSellCommand.onEdit(QuickSellCommand.java:59)
[13:44:38 WARN]:        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[13:44:38 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:577)
[13:44:38 WARN]:        at quicksell v2.3.4.jar//me.mrCookieSlime.QuickSell.acf.RegisteredCommand.invoke(RegisteredCommand.java:152)
[13:44:38 WARN]:        at quicksell v2.3.4.jar//me.mrCookieSlime.QuickSell.acf.BaseCommand.executeCommand(BaseCommand.java:577)
[13:44:38 WARN]:        at quicksell v2.3.4.jar//me.mrCookieSlime.QuickSell.acf.BaseCommand.execute(BaseCommand.java:513)
[13:44:38 WARN]:        at quicksell v2.3.4.jar//me.mrCookieSlime.QuickSell.acf.RootCommand.execute(RootCommand.java:99)
[13:44:38 WARN]:        at quicksell v2.3.4.jar//me.mrCookieSlime.QuickSell.acf.BukkitRootCommand.execute(BukkitRootCommand.java:81)
[13:44:38 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[13:44:38 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchCommand(CraftServer.java:929)
[13:44:38 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64)
[13:44:38 WARN]:        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264)
[13:44:38 WARN]:        at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:313)
[13:44:38 WARN]:        at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:297)
[13:44:38 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2288)
[13:44:38 WARN]:        at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$20(PlayerConnection.java:2248)
[13:44:38 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
[13:44:38 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[13:44:38 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[13:44:38 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[13:44:38 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[13:44:38 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1341)
[13:44:38 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)
[13:44:38 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[13:44:38 WARN]:        at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1318)
[13:44:38 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1311)
[13:44:38 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[13:44:38 WARN]:        at net.minecraft.server.MinecraftServer.i_(MinecraftServer.java:1289)
[13:44:38 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1177)
[13:44:38 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[13:44:38 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
quicksell reload
[13:44:59 WARN]: java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Method.invoke(Object, Object[])" because "me.mrCookieSlime.QuickSell.utils.StringUtils.getName" is null
[13:44:59 WARN]:        at quicksell v2.3.4.jar//me.mrCookieSlime.QuickSell.utils.StringUtils.formatItemName(StringUtils.java:32)
[13:44:59 WARN]:        at quicksell v2.3.4.jar//me.mrCookieSlime.QuickSell.PriceInfo.<init>(PriceInfo.java:49)
[13:44:59 WARN]:        at quicksell v2.3.4.jar//me.mrCookieSlime.QuickSell.Shop.<init>(Shop.java:37)
[13:44:59 WARN]:        at quicksell v2.3.4.jar//me.mrCookieSlime.QuickSell.QuickSell.reload(QuickSell.java:189)
[13:44:59 WARN]:        at quicksell v2.3.4.jar//me.mrCookieSlime.QuickSell.commands.QuickSellCommand.onReload(QuickSellCommand.java:36)
[13:44:59 WARN]:        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[13:44:59 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:577)
[13:44:59 WARN]:        at quicksell v2.3.4.jar//me.mrCookieSlime.QuickSell.acf.RegisteredCommand.invoke(RegisteredCommand.java:152)
[13:44:59 WARN]:        at quicksell v2.3.4.jar//me.mrCookieSlime.QuickSell.acf.BaseCommand.executeCommand(BaseCommand.java:577)
[13:44:59 WARN]:        at quicksell v2.3.4.jar//me.mrCookieSlime.QuickSell.acf.BaseCommand.execute(BaseCommand.java:513)
[13:44:59 WARN]:        at quicksell v2.3.4.jar//me.mrCookieSlime.QuickSell.acf.RootCommand.execute(RootCommand.java:99)
[13:44:59 WARN]:        at quicksell v2.3.4.jar//me.mrCookieSlime.QuickSell.acf.BukkitRootCommand.execute(BukkitRootCommand.java:81)
[13:44:59 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[13:44:59 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchCommand(CraftServer.java:929)
[13:44:59 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchServerCommand(CraftServer.java:892)
[13:44:59 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.bg(DedicatedServer.java:494)
[13:44:59 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:441)
[13:44:59 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1397)
[13:44:59 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1173)
[13:44:59 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[13:44:59 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[13:44:59 INFO]: All Shops have been reloaded!
quicksell reload
[13:45:00 WARN]: java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Method.invoke(Object, Object[])" because "me.mrCookieSlime.QuickSell.utils.StringUtils.getName" is null
[13:45:00 WARN]:        at quicksell v2.3.4.jar//me.mrCookieSlime.QuickSell.utils.StringUtils.formatItemName(StringUtils.java:32)
[13:45:00 WARN]:        at quicksell v2.3.4.jar//me.mrCookieSlime.QuickSell.PriceInfo.<init>(PriceInfo.java:49)
[13:45:00 WARN]:        at quicksell v2.3.4.jar//me.mrCookieSlime.QuickSell.Shop.<init>(Shop.java:37)
[13:45:00 WARN]:        at quicksell v2.3.4.jar//me.mrCookieSlime.QuickSell.QuickSell.reload(QuickSell.java:189)
[13:45:00 WARN]:        at quicksell v2.3.4.jar//me.mrCookieSlime.QuickSell.commands.QuickSellCommand.onReload(QuickSellCommand.java:36)
[13:45:00 WARN]:        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[13:45:00 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:577)
[13:45:00 WARN]:        at quicksell v2.3.4.jar//me.mrCookieSlime.QuickSell.acf.RegisteredCommand.invoke(RegisteredCommand.java:152)
[13:45:00 WARN]:        at quicksell v2.3.4.jar//me.mrCookieSlime.QuickSell.acf.BaseCommand.executeCommand(BaseCommand.java:577)
[13:45:00 WARN]:        at quicksell v2.3.4.jar//me.mrCookieSlime.QuickSell.acf.BaseCommand.execute(BaseCommand.java:513)
[13:45:00 WARN]:        at quicksell v2.3.4.jar//me.mrCookieSlime.QuickSell.acf.RootCommand.execute(RootCommand.java:99)
[13:45:00 WARN]:        at quicksell v2.3.4.jar//me.mrCookieSlime.QuickSell.acf.BukkitRootCommand.execute(BukkitRootCommand.java:81)
[13:45:00 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[13:45:00 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchCommand(CraftServer.java:929)
[13:45:00 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchServerCommand(CraftServer.java:892)
[13:45:00 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.bg(DedicatedServer.java:494)
[13:45:00 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:441)
[13:45:00 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1397)
[13:45:00 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1173)
[13:45:00 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[13:45:00 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[13:45:00 INFO]: All Shops have been reloaded!
## Environment (Required)

 - Minecraft Version: 1.19.3
 - QuickSell Version: 2.3.4

**Comment by PREMADESETUPS** [comment]
please fix this asap

**Comment by ShayPunter** [comment]
This has been resolved now
