### ISSUE TITLE
error 1.18.2 

### ISSUE THREAD

**Issue by kmai31e** [ShayPunter/QuickSell#7]
[12:10:14 WARN]: java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Method.invoke(Object, Object[])" because "me.mrCookieSlime.QuickSell.utils.StringUtils.getName" is null
[12:10:14 WARN]:        at quicksell v2.3.4.jar//me.mrCookieSlime.QuickSell.utils.StringUtils.formatItemName(StringUtils.java:32)
[12:10:14 WARN]:        at quicksell v2.3.4.jar//me.mrCookieSlime.QuickSell.PriceInfo.<init>(PriceInfo.java:49)
[12:10:14 WARN]:        at quicksell v2.3.4.jar//me.mrCookieSlime.QuickSell.Shop.<init>(Shop.java:37)
[12:10:14 WARN]:        at quicksell v2.3.4.jar//me.mrCookieSlime.QuickSell.QuickSell.reload(QuickSell.java:189)
[12:10:14 WARN]:        at quicksell v2.3.4.jar//me.mrCookieSlime.QuickSell.commands.QuickSellCommand.onReload(QuickSellCommand.java:36)
[12:10:14 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[12:10:14 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[12:10:14 WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[12:10:14 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[12:10:14 WARN]:        at quicksell v2.3.4.jar//me.mrCookieSlime.QuickSell.acf.RegisteredCommand.invoke(RegisteredCommand.java:152)
[12:10:14 WARN]:        at quicksell v2.3.4.jar//me.mrCookieSlime.QuickSell.acf.BaseCommand.executeCommand(BaseCommand.java:577)
[12:10:14 WARN]:        at quicksell v2.3.4.jar//me.mrCookieSlime.QuickSell.acf.BaseCommand.execute(BaseCommand.java:513)
[12:10:14 WARN]:        at quicksell v2.3.4.jar//me.mrCookieSlime.QuickSell.acf.RootCommand.execute(RootCommand.java:99)
[12:10:14 WARN]:        at quicksell v2.3.4.jar//me.mrCookieSlime.QuickSell.acf.BukkitRootCommand.execute(BukkitRootCommand.java:81)
[12:10:14 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[12:10:14 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:906)
[12:10:14 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2307)
[12:10:14 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2118)
[12:10:14 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2099)
[12:10:14 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[12:10:14 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[12:10:14 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:51)
[12:10:14 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[12:10:14 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[12:10:14 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[12:10:14 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1400)
[12:10:14 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188)
[12:10:14 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.y(IAsyncTaskHandler.java:126)
[12:10:14 WARN]:        at net.minecraft.server.MinecraftServer.be(MinecraftServer.java:1377)
[12:10:14 WARN]:        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1370)
[12:10:14 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[12:10:14 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1348)
[12:10:14 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1230)
[12:10:14 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[12:10:14 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by ShayPunter** [comment]
This has been resolved now
